# Generated by Django 4.2.5 on 2024-09-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0002_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
