# Generated by Django 4.2.5 on 2024-09-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychain', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
