# Generated by Django 4.2.5 on 2024-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('unitofmesurment', models.CharField(max_length=60)),
                ('quantity', models.FloatField(max_length=10)),
                ('price', models.FloatField(max_length=10)),
                ('supplierinfo', models.CharField(max_length=100)),
                ('reorderpoint', models.FloatField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'items',
            },
        ),
    ]
