# Generated by Django 4.2.5 on 2024-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description Product')),
                ('unitofmesurment', models.CharField(max_length=60, verbose_name='Unit Of Mesurment')),
                ('quantity', models.FloatField(max_length=10, verbose_name='Quantity')),
                ('price', models.FloatField(max_length=10, verbose_name='Price')),
                ('supplierinfo', models.CharField(max_length=100, verbose_name='Supplier Info')),
                ('reorderpoint', models.FloatField(max_length=10, verbose_name='Reorder Point')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('comments', models.CharField(max_length=100, verbose_name='Comments')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
