# Generated by Django 4.2.5 on 2024-02-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date',
        ),
    ]
