# Generated by Django 4.2.5 on 2024-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
