# Generated by Django 4.2.5 on 2024-02-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_unitofmesurment_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='unitofmesurment',
            options={'verbose_name_plural': 'Unitofmesurments'},
        ),
    ]
