# Generated by Django 4.2.5 on 2024-06-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
