# Generated by Django 4.2.5 on 2024-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, max_length=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
