# Generated by Django 4.2.5 on 2024-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Product ID'),
            preserve_default=False,
        ),
    ]
