# Generated by Django 4.2.5 on 2024-02-16 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customername', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('postalcode', models.CharField(max_length=20, verbose_name='Postal code')),
                ('customertitle', models.CharField(max_length=50, verbose_name='Customer title')),
                ('companyname', models.CharField(max_length=50, verbose_name='Company name')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
