# Generated by Django 4.2.5 on 2024-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
