# Generated by Django 4.2.5 on 2024-09-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
    ]
